### ISSUE TITLE
Wabbajack Download Error

### ISSUE THREAD

**Issue by areufo1312** [Kaethela/Starstruck-Courier#3]
"Waiting for patch processing on the server for Just Assorted Mods-66666-3-2c-1611922515.7z, sleeping for another 15 seconds"
Wabbajack downloads JAM and the EII patch, but returns this error. On retries with both files already present in the download path, Wabbajack attempts to download JAM again, and the error persists eventually resulting in "Installation Failed".
[Wabbajack.current.log](https://github.com/Kaethela/Starstruck-Courier/files/6683183/Wabbajack.current.log)

**Comment by Kaethela** [comment]
Looks like at least a few mods updated. Will push out an update when I can which should fix this.
