### ISSUE TITLE
Vanilla UI Plus Hash error (new version?)

### ISSUE THREAD

**Issue by vulcandth** [Kaethela/Starstruck-Courier#4]
I'm attempting to install Starstruck-Courier through wabbajack and i'm getting a file hash error with the mod Vanilla US Plus (New Vegas) 8.75. I believe this might be because the current version uploaded is now 8.75.76. See attached screenshots. 
I was hoping I could get this installed for my while to play tonight, but i'm not sure if that will happen now :(. Anyways thanks for your effort!

![SC-error-1](https://user-images.githubusercontent.com/6394873/124202617-53c56500-daa0-11eb-99a4-1ffb8ef342c9.png)
![SC-error-2](https://user-images.githubusercontent.com/6394873/124202618-545dfb80-daa0-11eb-82d7-c0335be6bc2b.png)

**Comment by Kaethela** [comment]
List update pushed, try again.
