### ISSUE TITLE
Fallout New California Install

### ISSUE THREAD

**Issue by Akoomer** [Kaethela/Starstruck-Courier#6]
I don't have the meta.ini file like you do in the screenshot, Im guessing that is the reason why my vigor tester section for New California is broken, how do I acquire said meta.ini?
![Screenshot 2021-08-23 201618](https://user-images.githubusercontent.com/89381943/130414065-e6023583-0f05-4a5d-9e9f-4f0e1e37d132.png)

**Comment by Kaethela** [comment]
The meta.ini file isn't needed and doesn't do anything in-game. The vigor section tends to break if SPECIAL points are at all different than what it expects. If you used any traits that give extra points, you can use the console to temporarily remove them and try again. Also, if you're on 50% XP gain that will also break it. It needs to be 100% until you've finished the FNC prologue.

**Comment by Akoomer** [comment]
its the 50% xp gain, ty for being so quick, turns out I cant read
